### ISSUE TITLE
Statting filename contains more than 2 slashes

### ISSUE THREAD

**Issue by AllanCat** [mon/ifs_layeredfs#2]
Screenshot:
![image](https://user-images.githubusercontent.com/1924514/98310142-36222780-2007-11eb-9c70-9b7cea0bda41.png)

Can temporary be fixed by editing modpath_handler's nuke double slash section(add /// to / or more generously keep nuking // until there's no more repeat slash).

**Comment by mon** [comment]
Fixed in a5af220bb29bea846d35373e3c86918448fc3181

Will do a release later when I decide how to fix the other problem you mentioned over discord. Can you make a separate issue for it?
