### ISSUE TITLE
Texturelist generates duplicated data_mods/{mod_name} path

### ISSUE THREAD

**Issue by AllanCat** [mon/ifs_layeredfs#3]
After demangling the path is data_mods/{mod_name}/{.ifs path}, when building texturelist, .ifs is replaced with _ifs and added available_mod's folder name, which causes "data_mods/{mod_name}/data_mods/{mod_name}/xxxx_ifs" path and missed hit.

This is related to the following issue:
When high priority _ifs and low priority .ifs both exists, ifs hook will pick low priority .ifs first
For example,
99/graphic/mdata.ifs
98/graphic/mdata_ifs/blah.png //this will not hit

My workaround right now is to remove the duplicated data_mods/{mod_name} in parse_texturelist() (as commit below)
https://github.com/AllanCat/ifs_layeredfs/commit/ab07405688ff87eade8ae6a22f2d56642fbdbf6a
But that seems not the right way to fix this issue.

**Comment by mon** [comment]
A thought that I never bothered to check - does the ramfs demangled layeredfs (v2.0 and up) fix this?

**Comment by AllanCat** [comment]
I just tested with v3.0 and the issue still exists. 
Furthermore, it seems commit [b8ef54e](https://github.com/mon/ifs_layeredfs/commit/b8ef54e61418779fe30e8cbedfd5d85aa7c037c2) broke this behavior even more.
I'm getting "Couldn't read prop" error log when I tried to load png on top of existing ifs file (iidx28).
My workaround method was also working until that commit.

**Comment by camprevail** [comment]
Can't you just merge or remove so either only .ifs files or _ifs folders exist? 
 
 
  On Sun, Oct 15, 2023 at 6:27 AM, ***@***.***> wrote:   


I just tested with v3.0 and the issue still exists.
Furthermore, it seems commit b8ef54e broke this behavior even more.
I'm getting "Couldn't read prop" error log when I tried to load png on top of existing ifs file.
My workaround method was also working until that commit.

**Comment by AllanCat** [comment]
For me there're two main reasons:
1. For convenience, being able to modify _ifs file on the fly on top of existing .ifs file without needing to repack every time.
2. I'm stacking each game versions using data_mods structure to save disk space. --layered-blocklist can be used to determine which version to run (by telling ifs_hook to only load up to specific version number).

And since reason 2. the ifs files with same name in data_mods is inevitable, at this state if I want to put stuff in _ifs then issue happens. Which means if I use this structure, then I won't be able to use _ifs feature at all.

**Comment by mon** [comment]
Fixed in e7018d9f4b3e5a9692e31c0cac1aa6e7831d10a6, thanks for waiting 3 years!
