### ISSUE TITLE
pkfs build still crashes GFDM V5 and V6

### ISSUE THREAD

**Issue by JamesLewisLiu** [mon/ifs_layeredfs#4]
Here's log, I have no time test V4 V7 V8 yet, maybe they will also crash
V5:
[ifs_hook.log](https://github.com/mon/ifs_layeredfs/files/15145519/ifs_hook.log)

V6:
[ifs_hook.log](https://github.com/mon/ifs_layeredfs/files/15145527/ifs_hook.log)

**Comment by mon** [comment]
Thanks for the logs, they've (hopefully) helped me pin down the issue. Try this: https://mon.im/ifs_layeredfs_3.4_RC2.zip

**Comment by JamesLewisLiu** [comment]
Thanks, now V5 and V6 seem work properly, will test V4 V7 V8 later

**Comment by JamesLewisLiu** [comment]
Now V4 V7 V8 XG1JP and XG1CN works fine, here's some log for reference
[ifs_hook_XG1.log](https://github.com/mon/ifs_layeredfs/files/15213439/ifs_hook_XG1.log)
[ifs_hook_XG1CN.log](https://github.com/mon/ifs_layeredfs/files/15213440/ifs_hook_XG1CN.log)
[ifs_hook_V8.log](https://github.com/mon/ifs_layeredfs/files/15213441/ifs_hook_V8.log)
[ifs_hook_V7.log](https://github.com/mon/ifs_layeredfs/files/15213442/ifs_hook_V7.log)
[ifs_hook_V4.log](https://github.com/mon/ifs_layeredfs/files/15213443/ifs_hook_V4.log)
